---
openapi: 3.0.1
info:
  title: Authentication API
  version: v1
paths:
  "/api/v1/authentication/login":
    post:
      summary: Authenticate an user
      tags:
      - Authentication
      parameters: []
      responses:
        '401':
          description: User or password invalid
          content:
            application/json:
              example:
                message: Usuário ou senha inválidos.
        '200':
          description: Informations loaded successfully
          content:
            application/json:
              example:
                id: 1
                email: user1@email.com
                fullName: Dra. Luan Raia
                token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NDE2NjAwODd9.m-s87IKA34NLu0BWcs2u9mFBviRXVa5T-b2I1OWSJdM
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
              required:
              - email
              - password
  "/api/v1/authentication/register":
    post:
      summary: Register an user
      tags:
      - Authentication
      parameters: []
      responses:
        '409':
          description: User already exists
          content:
            application/json:
              example:
                message: Usuário já existente
        '422':
          description: Invalid password
          content:
            application/json:
              example:
                message: 'A validação falhou: Senha necessita ter pelo menos 8 caracteres,
                  uma letra maiúscula, uma letra minúscula, um número e um caractere
                  especial'
                errors:
                  password:
                  - necessita ter pelo menos 8 caracteres, uma letra maiúscula, uma
                    letra minúscula, um número e um caractere especial
        '201':
          description: Created successfully
          content:
            application/json:
              example:
                id: 2
                email: keneth_huel@emmerich-goldner.test
                fullName: Luna Pedroso
                token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3NDE2NjAwODd9.-1Z7s6hq8fNUEjLmmGNqjyOSGyeW522OKkGvmCIza1s
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    full_name:
                      type: string
              required:
              - email
              - password
              - full_name
  "/":
    get:
      summary: Shows informations of API
      tags:
      - v1 API
      responses:
        '200':
          description: Informations loaded successfully
          content:
            application/json:
              example:
                version: 1.0.0
                message: Welcome to Handu API
                docs:
                  url: "/api-docs"
                  description: Handu API documentation
                maintaners:
                - ra: '23000201'
                  name: Everton Henrique Lopes
                  email: everton.lopes@sou.unifeob.edu.br
                - ra: '23000897'
                  name: Fábio Koiti Konda
                  email: fabio.konda@sou.unifeob.edu.br
                - ra: '23000019'
                  name: Lucas Pizol Ferreira
                  email: lucas.pizol@sou.unifeob.edu.br
                - ra: '23001518'
                  name: Mariana Franceschi Tessarini
                  email: mariana.tessarini@sou.unifeob.edu.br
                - ra: '23000825'
                  name: Yan Gomes Aguiar de Almeida
                  email: yan.aguiar@sou.unifeob.edu.br
                instituion:
                  name: Centro Universitário da Fundação de Ensino Octávio Bastos
                  acronym: UNIFEOB
                  url: https://www.unifeob.edu.br
  "/api/v1/translate_text":
    post:
      summary: Translate an text to another language
      tags:
      - Translate Text
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Translated successfully
          content:
            application/json:
              example:
                message: Olá, mundo!
        '400':
          description: Invalid language
          content:
            application/json:
              example:
                message: Linguagem de Destino não está incluído na lista
        '401':
          description: Expired or invalid session
          content:
            application/json:
              example:
                errors: Sessão expirada ou inválida.
        '422':
          description: Invalid params
          content:
            application/json:
              example:
                message: 'param is missing or the value is empty or invalid: translate'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                translate:
                  type: object
                  properties:
                    text:
                      type: string
                      example: Hello, world!
                    from_language:
                      type: string
                      example: en
                    to_language:
                      type: string
                      example: pt
                  required:
                  - text
                  - from_language
                  - to_language
              required:
              - translate
servers:
- url: http://localhost:8080
  variables:
    defaultHost:
      default: http://localhost:8080
