---
openapi: 3.0.1
info:
  title: Handu API
  version: v1
paths:
  "/api/v1/authentication/google":
    post:
      summary: Authenticate by google
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: Logged successfully
          content:
            application/json:
              example:
                id: 1
                email: user1@email.com
                fullName: Erick Tavares
                photoUrl:
                isEmailConfirmed: true
                token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NDMyODk4Nzh9.YXC_Ktw9RzXGFp52xP9wLLaQL41k0S_lntiQNAiyAF8
        '201':
          description: Created and logged successfully
          content:
            application/json:
              example:
                id: 1
                email: jaclyn.barrows@brekke-kuphal.example
                fullName: Maria Júlia Freitas
                photoUrl: http://kulas.example/diego
                isEmailConfirmed: true
                token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NDMyODk4Nzh9.YXC_Ktw9RzXGFp52xP9wLLaQL41k0S_lntiQNAiyAF8
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                message: Usuário ou senha inválidos.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    token:
                      type: string
                      example: E8v9azIrcCjLg7Yp
                  required:
                  - token
              required:
              - user
  "/api/v1/authentication/login":
    post:
      summary: Authenticate an user
      tags:
      - Authentication
      parameters: []
      responses:
        '401':
          description: User or password invalid
          content:
            application/json:
              example:
                message: Usuário ou senha inválidos.
        '200':
          description: Informations loaded successfully
          content:
            application/json:
              example:
                id: 1
                email: user2@email.com
                fullName: Theo Mendanha
                photoUrl:
                isEmailConfirmed: true
                token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NDMyODk4Nzh9.YXC_Ktw9RzXGFp52xP9wLLaQL41k0S_lntiQNAiyAF8
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      example: shaun@kohler.test
                    password:
                      type: string
                      example: ipDKqh22CK26z
              required:
              - email
              - password
  "/api/v1/authentication/register":
    post:
      summary: Register an user
      tags:
      - Authentication
      parameters: []
      responses:
        '409':
          description: User already exists
          content:
            application/json:
              example:
                message: Usuário já existente
        '422':
          description: Invalid password
          content:
            application/json:
              example:
                message: 'A validação falhou: Senha necessita ter pelo menos 8 caracteres,
                  uma letra maiúscula, uma letra minúscula, um número e um caractere
                  especial'
                errors:
                  password:
                  - necessita ter pelo menos 8 caracteres, uma letra maiúscula, uma
                    letra minúscula, um número e um caractere especial
        '201':
          description: Created successfully
          content:
            application/json:
              example:
                id: 2
                email: clifford@hintz-schowalter.example
                fullName: Srta. Melissa Raia
                photoUrl:
                isEmailConfirmed: false
                token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3NDMyODk4Nzh9.zzGavtIC-EWrJlTbPDKE1s7hAeIAA_o0J9VYYjcnV8c
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      example: stephane.klocko@runolfsdottir.test
                    password:
                      type: string
                      example: g10nXSgwRzVg
                    full_name:
                      type: string
                      example: Sra. Júlia Rodrigues
              required:
              - email
              - password
              - full_name
  "/api/v1/languages":
    get:
      summary: Loads all languages
      tags:
      - Languages
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Languages loaded
          content:
            application/json:
              example:
                languages:
                - acronym: en
                  name: Inglês
                - acronym: es
                  name: Espanhol
                - acronym: fr
                  name: Francês
                - acronym: de
                  name: Alemão
                - acronym: it
                  name: Italiano
                - acronym: ja
                  name: Japonês
                - acronym: ko
                  name: Coreano
                - acronym: pt
                  name: Português
                - acronym: ru
                  name: Russo
                - acronym: zh
                  name: Chinês
        '401':
          description: Expired or invalid session
          content:
            application/json:
              example:
                message: Sessão expirada ou inválida.
  "/":
    get:
      summary: Shows informations of API
      tags:
      - v1 API
      responses:
        '200':
          description: Informations loaded successfully
          content:
            application/json:
              example:
                version: 1.0.0
                message: Welcome to Handu API
                docs:
                  url: "/api-docs"
                  description: Handu API documentation
                maintaners:
                - ra: '23000201'
                  name: Everton Henrique Lopes
                  email: everton.lopes@sou.unifeob.edu.br
                - ra: '23000897'
                  name: Fábio Koiti Konda
                  email: fabio.konda@sou.unifeob.edu.br
                - ra: '23000019'
                  name: Lucas Pizol Ferreira
                  email: lucas.pizol@sou.unifeob.edu.br
                - ra: '23001518'
                  name: Mariana Franceschi Tessarini
                  email: mariana.tessarini@sou.unifeob.edu.br
                - ra: '23000825'
                  name: Yan Gomes Aguiar de Almeida
                  email: yan.aguiar@sou.unifeob.edu.br
                instituion:
                  name: Centro Universitário da Fundação de Ensino Octávio Bastos
                  acronym: UNIFEOB
                  url: https://www.unifeob.edu.br
  "/api/v1/translate_text":
    post:
      summary: Translate an text to another language
      tags:
      - Translate Text
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Translated successfully
          content:
            application/json:
              example:
                message: Olá, mundo!
        '400':
          description: Invalid language
          content:
            application/json:
              example:
                message: Linguagem de Destino não está incluído na lista
        '401':
          description: Expired or invalid session
          content:
            application/json:
              example:
                message: Sessão expirada ou inválida.
        '422':
          description: Invalid params
          content:
            application/json:
              example:
                message: 'param is missing or the value is empty or invalid: translate'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                translate:
                  type: object
                  properties:
                    text:
                      type: string
                      example: Hello, world!
                    from_language:
                      type: string
                      example: en
                      enum:
                      - en
                      - es
                      - fr
                      - de
                      - it
                      - ja
                      - ko
                      - pt
                      - ru
                      - zh
                    to_language:
                      type: string
                      example: pt
                      enum:
                      - en
                      - es
                      - fr
                      - de
                      - it
                      - ja
                      - ko
                      - pt
                      - ru
                      - zh
                  required:
                  - text
                  - from_language
                  - to_language
              required:
              - translate
  "/api/v1/users/confirm_email":
    post:
      summary: Confirm email
      tags:
      - Users
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Email confirmed successfully
          content:
            application/json:
              example:
                id: 1
                email: user9@email.com
                fullName: Luiza Lopes
                photoUrl:
                isEmailConfirmed: true
        '422':
          description: Invalid params
          content:
            application/json:
              example:
                message: 'param is missing or the value is empty or invalid: user'
        '401':
          description: Expired or invalid session
          content:
            application/json:
              example:
                message: Sessão expirada ou inválida.
        '409':
          description: Email already confirmed
          content:
            application/json:
              example:
                message: Email já confirmado
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    code:
                      type: string
                      example: '1234'
                  required:
                  - code
              required:
              - user
servers:
- url: http://localhost:8080
  variables:
    defaultHost:
      default: http://localhost:8080
