---
openapi: 3.0.1
info:
  title: Handu API
  version: v1
paths:
  "/api/v1/authentication/google":
    post:
      summary: Authenticate by google
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: Logged successfully
          content:
            application/json:
              example:
                id: 1
                email: user1@email.com
                fullName: Maria Santos
                photoUrl:
                isEmailConfirmed: true
                token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NDQzMzMwNDd9.4Du3lb0ZNGlzQoEIWtFRn3vBCwy0efP0RckmY85lTRY
        '201':
          description: Created and logged successfully
          content:
            application/json:
              example:
                id: 1
                email: marylee@nikolaus-mckenzie.example
                fullName: Roberto Bulhões
                photoUrl: http://ryan.test/claribel
                isEmailConfirmed: true
                token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NDQzMzMwNDd9.4Du3lb0ZNGlzQoEIWtFRn3vBCwy0efP0RckmY85lTRY
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                message: Usuário ou senha inválidos.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    token:
                      type: string
                      example: 8VkcQWFR9qE
                  required:
                  - token
              required:
              - user
  "/api/v1/authentication/login":
    post:
      summary: Authenticate an user
      tags:
      - Authentication
      parameters: []
      responses:
        '401':
          description: User or password invalid
          content:
            application/json:
              example:
                message: Usuário ou senha inválidos.
        '200':
          description: Informations loaded successfully
          content:
            application/json:
              example:
                id: 1
                email: user2@email.com
                fullName: Amanda Vieira
                photoUrl:
                isEmailConfirmed: true
                token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NDQzMzMwNDd9.4Du3lb0ZNGlzQoEIWtFRn3vBCwy0efP0RckmY85lTRY
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      example: gordon@rempel.test
                    password:
                      type: string
                      example: tNZJ40yD8XxAjJWz
              required:
              - email
              - password
  "/api/v1/authentication/register":
    post:
      summary: Register an user
      tags:
      - Authentication
      parameters: []
      responses:
        '409':
          description: User already exists
          content:
            application/json:
              example:
                message: Usuário já existente
        '422':
          description: Invalid password
          content:
            application/json:
              example:
                message: 'A validação falhou: Senha necessita ter pelo menos 8 caracteres,
                  uma letra maiúscula, uma letra minúscula, um número e um caractere
                  especial'
                errors:
                  password:
                  - necessita ter pelo menos 8 caracteres, uma letra maiúscula, uma
                    letra minúscula, um número e um caractere especial
        '201':
          description: Created successfully
          content:
            application/json:
              example:
                id: 2
                email: sylvie_gutkowski@jacobson-leannon.test
                fullName: Benício Beltrão Jr.
                photoUrl:
                isEmailConfirmed: false
                token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3NDQzMzMwNDd9.-xZ4nLxd8qhHva4iqJMuPpGECraSa3LudYM8Wk_kxu4
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      example: rosalina.sanford@tremblay.example
                    password:
                      type: string
                      example: WVUwdn5deyBi
                    full_name:
                      type: string
                      example: André Paiva Jr.
              required:
              - email
              - password
              - full_name
  "/api/v1/languages":
    get:
      summary: Loads all languages
      tags:
      - Languages
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Languages loaded
          content:
            application/json:
              example:
                languages:
                - acronym: en
                  name: Inglês
                - acronym: es
                  name: Espanhol
                - acronym: fr
                  name: Francês
                - acronym: de
                  name: Alemão
                - acronym: it
                  name: Italiano
                - acronym: ja
                  name: Japonês
                - acronym: ko
                  name: Coreano
                - acronym: pt
                  name: Português
                - acronym: ru
                  name: Russo
                - acronym: zh
                  name: Chinês
        '401':
          description: Expired or invalid session
          content:
            application/json:
              example:
                message: Sessão expirada ou inválida.
  "/":
    get:
      summary: Shows informations of API
      tags:
      - v1 API
      responses:
        '200':
          description: Informations loaded successfully
          content:
            application/json:
              example:
                version: 1.0.0
                message: Welcome to Handu API
                docs:
                  url: "/api-docs"
                  description: Handu API documentation
                maintaners:
                - ra: '23000201'
                  name: Everton Henrique Lopes
                  email: everton.lopes@sou.unifeob.edu.br
                - ra: '23000897'
                  name: Fábio Koiti Konda
                  email: fabio.konda@sou.unifeob.edu.br
                - ra: '23000019'
                  name: Lucas Pizol Ferreira
                  email: lucas.pizol@sou.unifeob.edu.br
                - ra: '23001518'
                  name: Mariana Franceschi Tessarini
                  email: mariana.tessarini@sou.unifeob.edu.br
                - ra: '23000825'
                  name: Yan Gomes Aguiar de Almeida
                  email: yan.aguiar@sou.unifeob.edu.br
                instituion:
                  name: Centro Universitário da Fundação de Ensino Octávio Bastos
                  acronym: UNIFEOB
                  url: https://www.unifeob.edu.br
  "/api/v1/trails":
    post:
      summary: Creates a trail
      tags:
      - Trails
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: Created successfully
          content:
            application/json:
              example:
                trail:
                  id: 1
                  name: Enim temporibus atque quos.
                  description: Quasi labore qui. Autem et voluptate. Eius nihil necessitatibus.
                  language:
                    name: Inglês
                    code: en
        '400':
          description: Bad request
          content:
            application/json:
              example:
                message: Linguagem não está incluído na lista
        '401':
          description: Expired or invalid session
          content:
            application/json:
              example:
                message: Sessão expirada ou inválida.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                trail:
                  type: object
                  properties:
                    language:
                      type: string
                      example: en
                      enum:
                      - en
                      - es
                      - fr
                      - de
                      - it
                      - ja
                      - ko
                      - pt
                      - ru
                      - zh
                  required:
                  - language
              required:
              - trail
    get:
      summary: Returns a list of trails
      tags:
      - Trails
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Returned successfully
          content:
            application/json:
              example:
                trails:
                - id: 1
                  name: Dolores magni dolore.
                  description: Sit sed et. Et molestias et.
                  language:
                    name: Inglês
                    code: en
                - id: 2
                  name: Impedit repellendus atque.
                  description: Id voluptate fugiat. Nihil vero sed.
                  language:
                    name: Inglês
                    code: en
                - id: 3
                  name: Quod dicta id.
                  description: Veritatis nihil nemo. Aut id esse.
                  language:
                    name: Inglês
                    code: en
        '401':
          description: Expired or invalid session
          content:
            application/json:
              example:
                message: Sessão expirada ou inválida.
  "/api/v1/trails/{id}":
    delete:
      summary: Deletes a trails
      tags:
      - Trails
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: ID of the trail to delete
        schema:
          type: integer
      responses:
        '204':
          description: Deleted successfully
        '401':
          description: Expired or invalid session
          content:
            application/json:
              example:
                message: Sessão expirada ou inválida.
        '404':
          description: Trail not found
          content:
            application/json:
              example:
                message: Trilha não encontrada
    get:
      summary: Show a trail
      tags:
      - Trails
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: ID of the trail to delete
        schema:
          type: integer
      responses:
        '200':
          description: Returned successfully
          content:
            application/json:
              example:
                trail:
                  id: 1
                  name: Ipsum mollitia qui.
                  description: Est praesentium suscipit. Eaque et iste.
                  language:
                    name: Inglês
                    code: en
        '401':
          description: Expired or invalid session
          content:
            application/json:
              example:
                message: Sessão expirada ou inválida.
        '404':
          description: Trail not found
          content:
            application/json:
              example:
                message: Trilha não encontrada
  "/api/v1/translate_text":
    post:
      summary: Translate an text to another language
      tags:
      - Translate Text
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Translated successfully
          content:
            application/json:
              example:
                message: Olá, mundo!
        '400':
          description: Invalid language
          content:
            application/json:
              example:
                message: Linguagem de Destino não está incluído na lista
        '401':
          description: Expired or invalid session
          content:
            application/json:
              example:
                message: Sessão expirada ou inválida.
        '422':
          description: Invalid params
          content:
            application/json:
              example:
                message: 'param is missing or the value is empty or invalid: translate'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                translate:
                  type: object
                  properties:
                    text:
                      type: string
                      example: Hello, world!
                    from_language:
                      type: string
                      example: en
                      enum:
                      - en
                      - es
                      - fr
                      - de
                      - it
                      - ja
                      - ko
                      - pt
                      - ru
                      - zh
                    to_language:
                      type: string
                      example: pt
                      enum:
                      - en
                      - es
                      - fr
                      - de
                      - it
                      - ja
                      - ko
                      - pt
                      - ru
                      - zh
                  required:
                  - text
                  - from_language
                  - to_language
              required:
              - translate
  "/api/v1/users/confirm_email":
    post:
      summary: Confirm email
      tags:
      - Users
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Email confirmed successfully
          content:
            application/json:
              example:
                id: 1
                email: user19@email.com
                fullName: Vinícius Brites
                photoUrl:
                isEmailConfirmed: true
        '401':
          description: Expired or invalid session
          content:
            application/json:
              example:
                message: Sessão expirada ou inválida.
        '409':
          description: Email already confirmed
          content:
            application/json:
              example:
                message: Email já confirmado
        '422':
          description: Invalid params
          content:
            application/json:
              example:
                message: 'param is missing or the value is empty or invalid: user'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    code:
                      type: string
                      example: '1234'
                  required:
                  - code
              required:
              - user
  "/api/v1/users/me":
    get:
      summary: Get user
      tags:
      - Users
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Get current user
          content:
            application/json:
              example:
                id: 1
                email: user22@email.com
                fullName: Srta. Lavínia Mangueira
                photoUrl:
                isEmailConfirmed: false
        '401':
          description: Expired or invalid session
          content:
            application/json:
              example:
                message: Sessão expirada ou inválida.
  "/api/v1/users/resend_email_confirmation":
    post:
      summary: Resend email confirmation
      tags:
      - Users
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Email confirmation sent
          content:
            application/json:
              example:
                message: E-mail de confirmação enviado com sucesso
        '401':
          description: Expired or invalid session
          content:
            application/json:
              example:
                message: Sessão expirada ou inválida.
        '409':
          description: Email already confirmed
          content:
            application/json:
              example:
                message: Email já confirmado
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: http://localhost:3000
