
require:
  - rubocop-rails
  - rubocop-performance

inherit_from:
  - ./rubocop/rubocop_style.yml

AllCops:
  TargetRubyVersion: 3.4.1
  Exclude:
    - 'config/**/*'
    - 'bundle_cache/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'bundle_cache/**/*'
    - 'bin/**/*'
    - '.bundle/*'
    - 'public/**/*'
    - 'lib/tasks/**/*'

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']

Metrics/MethodLength:
  Max: 20

Style/StringHashKeys:
  Enabled: false
