services:
  sst:
    build:
      context: "."
    image: backend-app
    command: server
    tty: true
    stdin_open: true
    volumes:
      - .:/sst
      - ./bundle_cache:/bundle:rw,delegated
    env_file:
      - .env

  nginx:
    image: nginx:1.19.4
    depends_on:
      - sst
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
