services:
  sst:
    build:
      context: "."
    image: backend-app
    command: server
    tty: true
    stdin_open: true
    volumes:
      - .:/sst
      - ./bundle_cache:/bundle:rw,delegated
    env_file:
      - .env

  nginx:
    image: nginx:1.19.4
    depends_on:
      - sst
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  sidekiq:
    depends_on:
      - "redis"
    image: backend-app
    command: sidekiq
    volumes:
      - .:/sst
      - ./bundle_cache:/bundle:rw,delegated
      - ./node_modules:/sst/node_modules:rw,delegated
    environment:
      REDIS_URL: redis://redis:6379/1
